# Assignment 4 Solution

# Method 1: Manual operations

In [3]:
import pandas as pd

df = pd.read_excel('E:\\Machine Learning Course\\Assignments\\Assignment 4 (data).xlsx')
df

Weight  Price
0       2     35
1       4     60
2       5     20
3       3     50
4       6     50
5       5     55
6       7     60

In [4]:
y = df['Price'] # df['Price'] returns a Pandas Series but df[['Price']] returns a Pandas DataFrame with a single column.
x = df['Weight']


In [5]:
x

0    2
1    4
2    5
3    3
4    6
5    5
6    7
Name: Weight, dtype: int64

In [6]:
y

0    35
1    60
2    20
3    50
4    50
5    55
6    60
Name: Price, dtype: int64

In [15]:
import numpy as np

In [17]:
mean_x = np.mean(x)
mean_y = np.mean(y)

In [18]:
mean_x

4.571428571428571

In [20]:
mean_y

47.142857142857146

In [21]:
dev_x = x - mean_x
dev_y = y - mean_y

In [22]:
dev_x

0   -2.571429
1   -0.571429
2    0.428571
3   -1.571429
4    1.428571
5    0.428571
6    2.428571
Name: Weight, dtype: float64

In [23]:
dev_y

0   -12.142857
1    12.857143
2   -27.142857
3     2.857143
4     2.857143
5     7.857143
6    12.857143
Name: Price, dtype: float64

1. Slope, m = Σ((x - x̄) * (y - ȳ)) / Σ((x - x̄)^2)
2. Intercept, c = ȳ - m * x̄

In [24]:
coefficient_m = np.sum(dev_x * dev_y) / np.sum(dev_x**2) 
coefficient_m

2.620967741935484

In [25]:
intercept_c = mean_y - (coefficient_m * mean_x)
intercept_c

35.16129032258065

# Task 01: Predicted price when the vegetable weight is 6.

In [26]:
Predicted_price =  (coefficient_m * 6) + intercept_c
Predicted_price

50.88709677419355

# Task 02: Residuals for each data point.

In [27]:
pred_y = (coefficient_m * x) + intercept_c
pred_y

0    40.403226
1    45.645161
2    48.266129
3    43.024194
4    50.887097
5    48.266129
6    53.508065
Name: Weight, dtype: float64

In [28]:
residuals = y - pred_y
residuals

0    -5.403226
1    14.354839
2   -28.266129
3     6.975806
4    -0.887097
5     6.733871
6     6.491935
dtype: float64

# Task 03: MSE and MAE

In [29]:
MAE = np.sum(abs(residuals))/len(x)
MAE

9.87327188940092

In [30]:
MSE = np.sum(residuals**2)/len(x)
MSE

167.30990783410135

# 2nd Method: Using sklearn Linear Model

In [9]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()

In [11]:
reg.fit(df[['Weight']] , df[['Price']])

LinearRegression()

In [12]:
reg.coef_

array([[2.62096774]])

In [13]:
reg.intercept_


array([35.16129032])

# Task 01: Predicted price when the vegetable weight is 6.

In [39]:
# Task 01: Predicted price when the vegetable weight is 6.
reg.predict([[6]])

C:\ProgramData\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[50.88709677]])

# Task 02: Residuals for each data point.

In [40]:
df['predicted_price'] = reg.predict(df[['Weight']])

In [41]:
df

Weight  Price  predicted_price
0       2     35        40.403226
1       4     60        45.645161
2       5     20        48.266129
3       3     50        43.024194
4       6     50        50.887097
5       5     55        48.266129
6       7     60        53.508065

In [42]:
df['residuals'] = df['Price'] - df['predicted_price']

df

Weight  Price  predicted_price  residuals
0       2     35        40.403226  -5.403226
1       4     60        45.645161  14.354839
2       5     20        48.266129 -28.266129
3       3     50        43.024194   6.975806
4       6     50        50.887097  -0.887097
5       5     55        48.266129   6.733871
6       7     60        53.508065   6.491935

# Task 03: MSE and MAE

In [43]:
#mse
from sklearn.metrics import mean_squared_error

In [44]:
MSE = mean_squared_error(df['Price'],df['predicted_price'])
MSE

167.30990783410135

In [45]:
#mae
from sklearn.metrics import mean_absolute_error
MAE = mean_absolute_error(df['Price'],df['predicted_price'])
MAE

9.87327188940092